LectureSchedulingTool/Models/Scheduling/SchedulingAlgorithm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Configuration;

namespace LectureSchedulingTool.Models
{
    public class SchedulingAlgorithm
    {
        public void Generate()
        {
            using (var DB = new SchedulingContext())
            {
                List<Students_Group_Day> sg_day = new List<Students_Group_Day>();
                foreach (var sg in DB.Students_group)
                    sg_day.Add(new Students_Group_Day(sg.id_students_group));

                List<Teacher_Day> t_day = new List<Teacher_Day>();
                foreach (var t in DB.Teacher)
                    t_day.Add(new Teacher_Day(t.id_teacher));

                List<Classroom_Day> c_day = new List<Classroom_Day>();
                foreach (var c in DB.Classroom)
                    c_day.Add(new Classroom_Day(c.id_classroom));

                foreach (var d in DB.Department)
                {

                }

                foreach (var d in DB.Department)
                {
                    List<SVM.Lesson> empty_lessons = GetEmptyLessons(d.id_department, true);

                    while (empty_lessons.Count > 0)
                    {

                    }
                }
            }
        }

        private class Students_Group_Day
        {
            public readonly int id_students_group;

            List<List<bool>> day;

            public Students_Group_Day(int id_students_group)
            {
                this.id_students_group = id_students_group;

                day = new List<List<bool>>(5);

                int lessons = Int32.Parse(ConfigurationManager.AppSettings["LessonsCount"]);

                for (int i = 0; i < 5; i++)
                {
                    day.Add(new List<bool>(lessons));

                    for (int j = 0; j < lessons; j++)
                        day[i].Add(false);
                }
            }
        }
        private class Teacher_Day
        {
            public readonly int id_teacher;

            List<List<bool>> day;

            public Teacher_Day(int id_teacher)
            {
                this.id_teacher = id_teacher;

                day = new List<List<bool>>();

                int lessons = Int32.Parse(ConfigurationManager.AppSettings["LessonsCount"]);

                for (int i = 0; i < 5; i++)
                {
                    day.Add(new List<bool>(lessons));

                    for (int j = 0; j < lessons; j++)
                        day[i].Add(false);
                }
            }
        }
        private class Classroom_Day
        {
            public readonly int id_classroom;

            List<List<bool>> day;

            public Classroom_Day(int id_classroom)
            {
                this.id_classroom = id_classroom;

                day = new List<List<bool>>();

                int lessons = Int32.Parse(ConfigurationManager.AppSettings["LessonsCount"]);

                for (int i = 0; i < 5; i++)
                {
                    day.Add(new List<bool>(lessons));

                    for (int j = 0; j < lessons; j++)
                        day[i].Add(false);
                }
            }
        }

        private List<SVM.Lesson> GetEmptyLessons(int id_department, bool for_internal_groups)
        {
            List<SVM.Students_group_load> student_group_loads;
            List<SVM.Lesson> lessons = new List<SVM.Lesson>();

            using (var DB = new SchedulingContext())
            {
                student_group_loads = new List<SVM.Students_group_load>(DB.Students_group_load.Count());

                student_group_loads = DB.Students_group_load.Take(16).ToList();
            }

            int weeks_amount = Int32.Parse(ConfigurationManager.AppSettings["WeeksAmount"]);
            int weeks_count = Int32.Parse(ConfigurationManager.AppSettings["WeeksCount"]);
            int lesson_amount = Int32.Parse(ConfigurationManager.AppSettings["LessonsAmount"]);

            int min_hours = weeks_amount * lesson_amount / weeks_count;

            for (int i = 0; student_group_loads.Count != 0; i++)
            {
                if (student_group_loads[i].hours / min_hours == 1)
                {
                    lessons.Add(new SVM.Lesson { id_students_group_load = student_group_loads[i].id_students_group_load });
                    student_group_loads.Remove(student_group_loads[i]);
                }
                else
                {
                    lessons.Add(new SVM.Lesson { id_students_group_load = student_group_loads[i].id_students_group_load });
                    student_group_loads[i].hours -= min_hours;
                }
            }

            return lessons;
        }
    }
}

LectureSchedulingTool/Models/Scheduling/SchedulingContext.cs
using System.Collections.Generic;
using System.Data.Entity;

namespace LectureSchedulingTool.Models
{
    //Модель базы данных
    public class SchedulingContext : DbContext
    {
        public DbSet<SVM.Faculty> Faculty { get; set; }
        public DbSet<SVM.Department> Department { get; set; }
        public DbSet<SVM.Students_group> Students_group { get; set; }
        public DbSet<SVM.Teacher> Teacher { get; set; }
        public DbSet<SVM.Subject> Subject { get; set; }
        public DbSet<SVM.Classroom> Classroom { get; set; }
        public DbSet<SVM.Students_group_load> Students_group_load { get; set; }
        public DbSet<SVM.Teacher_load> Teacher_load { get; set; }
        public DbSet<SVM.Lesson> Lesson { get; set; }
    }
}

LectureSchedulingTool/Controllers/SchedulingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using LectureSchedulingTool.Models;

namespace LectureSchedulingTool.Controllers
{
    [Authorize]
    public partial class SchedulingController : Controller
    {
        private static SchedulingContext DB = new SchedulingContext();
        public string CurrentLangCode { get; protected set; }
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            //проверяем если ли в коллекции параметр lang и если есть, получаем его.
            if (requestContext.RouteData.Values["lang"] != null && requestContext.RouteData.Values["lang"] as string != "null")
            {
                CurrentLangCode = requestContext.RouteData.Values["lang"] as string;
            }
            //а если его нет, то используем язык по умолчанию
            else
                CurrentLangCode = "ru";

            //сохраняем значение языка во ViewBag, для того, чтобы легко получать к нему доступ из вьюшки
            ViewBag.CurLang = CurrentLangCode;

            string cultureName = (string)requestContext.RouteData.Values["lang"];
            Localizator.Initialize(cultureName);

            base.Initialize(requestContext);
        }

        public ActionResult GetDepartments(int id_faculty)
        {
            using (var DB = new SchedulingContext())
            {
                ViewBag.departments = DB.Department.Where(d => d.id_faculty == id_faculty).ToList();

                return PartialView();
            }
        }

        public ActionResult GetTeachers(int id_department)
        {
            using (var DB = new SchedulingContext())
            {
                ViewBag.teachers = DB.Teacher.Where(t => t.id_department == id_department).ToList();

                return PartialView();
            }
        }

        public ActionResult GetSubjects(int id_department)
        {
            using (var DB = new SchedulingContext())
            {
                ViewBag.subjects = DB.Subject.Where(s => s.id_department == id_department).ToList();

                return PartialView();
            }
        }

        public IQueryable<SVM.Faculty> GetOnlyNeedsFaculties(IQueryable<SVM.Department> departments)
        {
            return (from f in DB.Faculty join d in departments on f.id_faculty equals d.id_faculty select f);
        }
        public IQueryable<SVM.Department> GetOnlyNeedsDepartments(IQueryable<SVM.Students_group> students_groups)
        {
            return (from d in DB.Department join sg in students_groups on d.id_department equals sg.id_department select d);
        }
        public IQueryable<SVM.Department> GetOnlyNeedsDepartments(IQueryable<SVM.Teacher> teachers)
        {
            return (from d in DB.Department join t in teachers on d.id_department equals t.id_department select d);
        }
        public IQueryable<SVM.Department> GetOnlyNeedsDepartments(IQueryable<SVM.Subject> subjects)
        {
            return (from d in DB.Department join s in subjects on d.id_department equals s.id_department select d);
        }
        public IQueryable<SVM.Department> GetOnlyNeedsDepartments(IQueryable<SVM.Classroom> classrooms)
        {
            return (from d in DB.Department join c in classrooms on d.id_department equals c.id_department select d);
        }
        public IQueryable<SVM.Students_group> GetOnlyNeedsStudentsGroups(IQueryable<SVM.Students_group_load> students_group_load)
        {
            return (from sg in DB.Students_group join sgl in students_group_load on sg.id_students_group equals sgl.id_students_group select sg);
        }
        public IQueryable<SVM.Teacher> GetOnlyNeedsTeachers(IQueryable<SVM.Teacher_load> teacher_load)
        {
            return (from t in DB.Teacher join tl in teacher_load on t.id_teacher equals tl.id_teacher select t);
        }
        public IQueryable<SVM.Subject> GetOnlyNeedsSubjects(IQueryable<SVM.Students_group_load> students_group_load)
        {
            return (from s in DB.Subject join sgl in students_group_load on s.id_subject equals sgl.id_subject select s);
        }
        public IQueryable<SVM.Subject> GetOnlyNeedsSubjects(IQueryable<SVM.Teacher_load> teacher_load)
        {
            return (from s in DB.Subject join tl in teacher_load on s.id_subject equals tl.id_subject select s);
        }

        public IQueryable<SVM.Faculty> GetSafeFaculties()
        {
            return DB.Faculty;
        }
        public IQueryable<SVM.Department> GetSafeDepartmentsForSGLoads()
        {
            return DB.Department;
        }
        public IQueryable<SVM.Department> GetSafeDepartmentsForTLoads()
        {
            return DB.Department;
        }
    }
}

LectureSchedulingTool/Controllers/SchedulingView/ClassroomController.cs
using LectureSchedulingTool.Models;
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace LectureSchedulingTool.Controllers
{
    public partial class SchedulingController : Controller
    {
        [Authorize]
        public ActionResult Classroom(SVM.Classroom model, int page = 1, char action = '0', int row = -1, int id_classroom = -1)
        {
            switch (action)
            {
                case 'a':
                    ModelState.Clear();

                    ViewBag.action = action;
                    ViewBag.row = row;

                    model = new SVM.Classroom();
                    break;

                case 's':
                    if (ModelState.IsValid)
                    {
                        if (DB.Classroom.Count(c => c.number == model.number) > 0)
                        {
                            ViewBag.action = 'a';
                            ViewBag.row = row;

                            ModelState.AddModelError("-2", Localizator.Localizate("Classroom_duplicate_number_error", CurrentLangCode));
                        }
                        else
                        {
                            ViewBag.action = '0';
                            ViewBag.row = -1;

                            try
                            {
                                DB.Classroom.Add(model);
                                DB.SaveChanges();
                            }
                            catch (Exception ex)
                            {
                                ModelState.AddModelError("-3", Localizator.Localizate("Classroom_add_error", CurrentLangCode));
                                if (HttpContext.IsDebuggingEnabled)
                                    ModelState.AddModelError("-3", ex.GetBaseException().Message);
                            }
                        }
                    }
                    else
                    {
                        ViewBag.action = 'a';
                        ViewBag.row = row;
                    }
                    break;

                case 'e':
                    ModelState.Clear();

                    ViewBag.action = action;
                    ViewBag.row = row;

                    model = DB.Classroom.Find(id_classroom);
                    break;

                case 'u':
                    if (ModelState.IsValid)
                    {
                        if (DB.Classroom.Count(c => c.number == model.number && c.id_classroom != model.id_classroom) > 0)
                        {
                            ViewBag.action = 'e';
                            ViewBag.row = row;

                            ModelState.AddModelError("-2", Localizator.Localizate("Classroom_duplicate_number_error", CurrentLangCode));
                        }
                        else
                        {
                            ViewBag.action = '0';
                            ViewBag.row = -1;

                            try
                            {
                                DB.Classroom.Find(id_classroom).number = model.number;
                                DB.Classroom.Find(id_classroom).people_capacity = model.people_capacity;
                                DB.Classroom.Find(id_classroom).id_department = model.id_department;
                                DB.SaveChanges();
                            }
                            catch (Exception ex)
                            {
                                ModelState.AddModelError("-3", Localizator.Localizate("Classroom_edit_error", CurrentLangCode));
                                if (HttpContext.IsDebuggingEnabled)
                                    ModelState.AddModelError("-3", ex.GetBaseException().Message);
                            }
                        }
                    }
                    else
                    {
                        ViewBag.action = 'e';
                        ViewBag.row = row;
                    }
                    break;

                case 'r':
                    ModelState.Clear();
                    model = DB.Classroom.Find(id_classroom);
                    if (DB.Classroom.Count(c => c.number == model.number) > 0)
                    {
                        try
                        {
                            DB.Classroom.Remove(DB.Classroom.Find(id_classroom));
                            DB.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            ModelState.AddModelError("-4", Localizator.Localizate("Classroom_delete_error", CurrentLangCode));
                            if (HttpContext.IsDebuggingEnabled)
                                ModelState.AddModelError("-4", ex.GetBaseException().Message);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("-5", Localizator.Localizate("Classroom_existance_error", CurrentLangCode));
                    }
                    break;

                default:
                    ModelState.Clear();

                    ViewBag.action = '0';
                    ViewBag.row = -1;
                    break;
            }

            try
            {
                IQueryable<SVM.Classroom> Iclassrooms;

                int elements_on_page = Int32.Parse(ConfigurationManager.AppSettings["ElementsOnPage"]);
                if (DB.Classroom.Count() <= elements_on_page)
                {
                    ViewBag.pages = 1;
                    Iclassrooms = DB.Classroom;
                }
                else
                {
                    int pages = (DB.Classroom.Count() / elements_on_page) + 1;

                    ViewBag.elements_on_page = elements_on_page;
                    ViewBag.page = page;
                    ViewBag.pages = pages;

                    if (page == 1)
                        Iclassrooms = DB.Classroom.Take(elements_on_page);
                    else
                    {
                        if (page == pages)
                            Iclassrooms = DB.Classroom.OrderBy(c => c.id_classroom).Skip(elements_on_page * (page - 1));
                        else
                            Iclassrooms = DB.Classroom.OrderBy(c => c.id_classroom).Skip(elements_on_page * (page - 1)).Take(elements_on_page);
                    }
                }

                ViewBag.classrooms = Iclassrooms.ToList();
                ViewBag.departments = DB.Department.ToList();
                ViewBag.faculties = DB.Faculty.ToList();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("-1", Localizator.Localizate("Classroom_view_error", CurrentLangCode));
                if (HttpContext.IsDebuggingEnabled)
                    ModelState.AddModelError("-1", ex.GetBaseException().Message);
            }

            return View(model);
        }
    }
}

LectureSchedulingTool/Views/Scheduling/Classroom.cshtml
@using LectureSchedulingTool.Models;
@model SVM.Classroom

<h2> @Html.Localizate("ClassRooms", (string)ViewBag.CurLang) </h2>
<hr />

@(Html.ValidationSummary("", new { @class = "text-danger" }))

<table class="table-bordered table-condensed" align="center" width="100%">
    <thead>
        <tr>
            <td><center>№</center></td>
            <td>@Html.Localizate("Faculty", (string)ViewBag.CurLang)</td>
            <td>@Html.Localizate("Department", (string)ViewBag.CurLang)</td>
            <td>@Html.Localizate("Number", (string)ViewBag.CurLang)</td>
            <td>@Html.Localizate("Capacity", (string)ViewBag.CurLang)</td>
        </tr>
    </thead>
    <tbody>
        @{
            string action = ViewBag.action != null ? ViewBag.action.ToString() : "0";
            int edit_row = ViewBag.row != null ? ViewBag.row : -1;
            int elements_on_page = ViewBag.elements_on_page != null ? ViewBag.elements_on_page : 10;
            int page = ViewBag.page != null ? ViewBag.page : 1;
            int pages = ViewBag.pages != null ? ViewBag.pages : 1;

            List<SVM.Classroom> classrooms = ViewBag.classrooms != null ? ViewBag.classrooms : null;

            IEnumerable<SelectListItem> Ifaculties;
            IEnumerable<SelectListItem> Idepartments;

            for (int i = 0; i < classrooms.Count; i++)
            {
                if (action == "e" && edit_row == i)
                {
                    Ifaculties = (ViewBag.faculties as List<SVM.Faculty>).Select(f => new SelectListItem() { Value = f.id_faculty.ToString(), Text = f.ToString() });
                    Idepartments = (ViewBag.departments as List<SVM.Department>).Select(d => new SelectListItem() { Value = d.id_department.ToString(), Text = d.ToString() });

                    using (Html.BeginForm("Classroom", "Scheduling"))
                    {
                        <tr>
                            <input type="hidden" name="page" value="@(page)" />
                            <input type="hidden" name="row" value="@(i)" />
                            <input type="hidden" name="id_classroom" value="@(classrooms[i].id_classroom)" />
                            <td><center>@(i + (elements_on_page * (page - 1)) + 1) </center></td>
                            <td>@(Html.DropDownList("id_faculty", Ifaculties, new { @class = "form-control" }))</td>
                            <td>@(Html.DropDownListFor(m => m.id_department, Idepartments, new { @class = "form-control" }))</td>
                            <td>@(Html.TextBoxFor(m => m.number, new { @class = "form-control" })) </td>
                            <td>@(Html.TextBoxFor(m => m.people_capacity, new { @class = "form-control" })) </td>
                            <td width="10%"><center><button type="submit" id="update" name="action" value="u" class="btn btn-primary"> @Html.Localizate("Update", (string)ViewBag.CurLang)</button></center></td>
                            <td width="9%"><center><button type="submit" id="cancel" name="action" value="0" class="btn btn-warning"> @Html.Localizate("Cancel", (string)ViewBag.CurLang)</button></center></td>
                        </tr>
                    }
                }
                else
                {
                    SVM.Faculty faculty = classrooms[i].GetFaculty();
                    SVM.Department department = classrooms[i].GetDepartment();

                    using (Html.BeginForm("Classroom", "Scheduling"))
                    {
                        <tr>
                            <input type="hidden" name="page" value="@(page)" />
                            <input type="hidden" name="row" value="@(i)" />
                            <input type="hidden" name="id_classroom" value="@(classrooms[i].id_classroom)" />
                            <td><center>@(i + (elements_on_page * (page - 1)) + 1)</center></td>
                            <td>@(faculty.abbreviation)</td>
                            <td>@(department.abbreviation)</td>
                            <td>@(classrooms[i].number)</td>
                            <td>@(classrooms[i].people_capacity)</td>
                            @if (action == "e" || action == "a")
                            {
                                <td width="10%"><center><button type="submit" id="edit" name="action" value="e" class="btn btn-primary" width="inherit" disabled> @Html.Localizate("Edit", (string)ViewBag.CurLang)</button></center></td>
                                <td width="9%"><center><button type="submit" id="remove" name="action" value="r" class="btn btn-danger" width="inherit" disabled> @Html.Localizate("Remove", (string)ViewBag.CurLang)</button></center></td>
                            }
                            else
                            {
                                <td width="10%"><center><button type="submit" id="edit" name="action" value="e" class="btn btn-primary" width="inherit"> @Html.Localizate("Edit", (string)ViewBag.CurLang)</button></center></td>
                                <td width="9%"><center><button type="submit" id="remove" name="action" value="r" class="btn btn-danger" width="inherit"> @Html.Localizate("Remove", (string)ViewBag.CurLang)</button></center></td>
                            }
                        </tr>
                    }
                }
            }
            if (action == "a")
            {
                Ifaculties = (ViewBag.faculties as List<SVM.Faculty>).Select(f => new SelectListItem() { Value = f.id_faculty.ToString(), Text = f.ToString() });
                Idepartments = (ViewBag.departments as List<SVM.Department>).Select(d => new SelectListItem() { Value = d.id_department.ToString(), Text = d.ToString() });

                using (Html.BeginForm("Classroom", "Scheduling"))
                {
                    <tr>
                        <input type="hidden" name="page" value="@(page)" />
                        <td><center>* </center></td>
                        <td>@(Html.DropDownList("id_faculty", Ifaculties, new { @class = "form-control" }))</td>
                        <td>@(Html.DropDownListFor(m => m.id_department, Idepartments, new { @class = "form-control" }))</td>
                        <td>@(Html.TextBoxFor(m => m.number, new { @class = "form-control" })) </td>
                        <td>@(Html.TextBoxFor(m => m.people_capacity, new { @class = "form-control" })) </td>
                        <td width="10%"><center><button type="submit" id="save" name="action" value="s" class="btn btn-primary"> @Html.Localizate("Add", (string)ViewBag.CurLang)</button></center></td>
                        <td width="9%"><center><button type="submit" id="cancel" name="action" value="0" class="btn btn-warning"> @Html.Localizate("Cancel", (string)ViewBag.CurLang)</button></center></td>
                    </tr>
                }
            }
            using (Html.BeginForm("Classroom", "Scheduling"))
            {
                <tr>
                    <input type="hidden" name="page" value="@(page)" />
                    @if (action == "e" || action == "a")
                    {
                        <td width="3%"><button type="submit" id="add" name="action" value="a" class="btn btn-info" disabled> + </button></td>
                    }
                    else
                    {
                        <td width="3%"><button type="submit" id="add" name="action" value="a" class="btn btn-info"> + </button></td>
                    }
                </tr>
            }
        }
    </tbody>
</table>

@{
    if (pages != 1)
    {
        using (Html.BeginForm("Classroom", "Scheduling"))
        {
            <hr />
            <table>
                <tr>
                    <td><button type="submit" id="page" name="page" value="1" class="btn btn-default"> <<</button></td>
                    @for (int i = 1; i <= pages; i++)
                    {
                        if (i == page)
                        {
                            <td><button type="submit" id="page" name="page" value="@(i)" class="btn btn-info"> @(i) </button></td>
                        }
                        else
                        {
                            <td><button type="submit" id="page" name="page" value="@(i)" class="btn btn-default"> @(i) </button></td>
                        }
                    }
                    <td><button type="submit" id="page" name="page" value="@(pages)" class="btn btn-default"> >> </button></td>
                </tr>
            </table>
        }

        <input type="hidden" name="page" value="@(page)" />
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/Scheduling/scheduling_remove_alert.js"></script>
<script src="~/Scripts/Scheduling/scheduling_department_dynamic.js"></script>
<input name="department_list_getter" id="department_list_getter" type="hidden" value="@Url.Action("GetDepartments", "Scheduling")" />

LectureSchedulingTool/Views/Scheduling/GetDepartments.cshtml
@using LectureSchedulingTool.Models

@{
    List<SVM.Department> departments = ViewBag.departments;

    if (departments.Count != 0)
    {
        for (int i = 0; i < departments.Count; i++)
        {
            <option value="@departments[i].id_department" >
                @(departments[i].ToString())
            </option>
        }
    }
    else
    {
        <option value="-1">
           ------
        </option>
    }
}

LectureSchedulingTool/Views/Scheduling/GetSubjects.cshtml
@using LectureSchedulingTool.Models

@{
    List<SVM.Subject> subjects = ViewBag.subjects;

    if(subjects.Count != 0) { 

        for (int i = 0; i < subjects.Count; i++)
        {
            <option value="@subjects[i].id_subject">
                @(subjects[i].ToString())
            </option>
        }
    }
    else
    {
        <option value="-1">
            ------
        </option>
    }
}

LectureSchedulingTool/Views/Scheduling/GetTeachers.cshtml
@using LectureSchedulingTool.Models

@{
    List<SVM.Teacher> teachers = ViewBag.teachers;
    if (teachers.Count != 0) { 
        for (int i = 0; i < teachers.Count; i++)
        {
            <option value="@teachers[i].id_teacher">
                @(teachers[i].ToString())
            </option>
        }
    }
    else
    {
        <option value="-1">
           ------
        </option>
    }
}